<?php

return [
    'VALID' => '0',
    'INVALID_PASSWORD' => '1',
    'NOT_SAME_PASSWORD' => '2',
    'INVALID_KEY' => '3',
    'STATUS_ENSEIGNANT' => '4',
    'STATUS_ETUDIANT' => '5',
    'STATUS_PARTICULIER' => '6',
    'ROLE_ADMIN' => '7',
    'ROLE_DEV' => '8',
    'TYPE_CLASSROOM' => '9',
    'TYPE_PROJET' => '10',
    'INVALID_EMAIL' => '11',
    'ACCESS_DENIED' => '12',
    'INVALID_PROJECT' => '13',
    'ALREADY_AUTHORIZED' => '14',
    'UNKNOWN_USER' => '15',
    'RUN_ERROR' => '16',
    'BUILD_ERROR' => '17',
    'DOCKER_ERROR' => '18',
    'EXTENSION_ERROR'=> '19',
    'SIZE_ERROR' => '20',
    'ALREADY_ADD' => '21',
    'CHAMP_VIDE' => '22',
    'CLE_INVALIDE' => '23',
    'UNKNOWN_MAIL' => '24',
    'UNWANTED_ARRAY' => array(    'Š'=>'S', 'š'=>'s', 'Ž'=>'Z', 'ž'=>'z', 'À'=>'A', 'Á'=>'A', 'Â'=>'A', 'Ã'=>'A', 'Ä'=>'A', 'Å'=>'A', 'Æ'=>'A', 'Ç'=>'C', 'È'=>'E', 'É'=>'E',
                    'Ê'=>'E', 'Ë'=>'E', 'Ì'=>'I', 'Í'=>'I', 'Î'=>'I', 'Ï'=>'I', 'Ñ'=>'N', 'Ò'=>'O', 'Ó'=>'O', 'Ô'=>'O', 'Õ'=>'O', 'Ö'=>'O', 'Ø'=>'O', 'Ù'=>'U',
                    'Ú'=>'U', 'Û'=>'U', 'Ü'=>'U', 'Ý'=>'Y', 'Þ'=>'B', 'ß'=>'Ss', 'à'=>'a', 'á'=>'a', 'â'=>'a', 'ã'=>'a', 'ä'=>'a', 'å'=>'a', 'æ'=>'a', 'ç'=>'c',
                    'è'=>'e', 'é'=>'e', 'ê'=>'e', 'ë'=>'e', 'ì'=>'i', 'í'=>'i', 'î'=>'i', 'ï'=>'i', 'ð'=>'o', 'ñ'=>'n', 'ò'=>'o', 'ó'=>'o', 'ô'=>'o', 'õ'=>'o',
                    'ö'=>'o', 'ø'=>'o', 'ù'=>'u', 'ú'=>'u', 'û'=>'u', 'ý'=>'y', 'þ'=>'b', 'ÿ'=>'y' ),
];
